# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: /
    weight: 10

  - name: 关于我们
    identifier: 关于我们
    weight: 20
  - name: 中心简介
    parent: 关于我们
    url: /#intro
    weight: 10
  - name: 组织框架
    parent: 关于我们
    url: /people/institution/
    weight: 20
  - name: 大事记
    parent: 关于我们
    url: /#journey
    weight: 30
  - name: 合作伙伴
    parent: 关于我们
    url: /#partners
    weight: 40
  - name: 研究方向
    parent: 关于我们
    url: /#research-areas
    weight: 50
  - name: 联系我们
    parent: 关于我们
    url: /contact/
    weight: 60


  - name: 新闻动态
    identifier: 新闻动态
    weight: 30
  - name: 科研动态
    parent: 新闻动态
    url: /achievements/
    weight: 10
  - name: 学术活动
    parent: 新闻动态
    url: /events/
    weight: 20
  - name: 中心新闻
    parent: 新闻动态
    url: /news/
    weight: 30
  - name: 通知公告
    parent: 新闻动态
    url: /announcements/
    weight: 40


  - name: 人才队伍
    identifier: 人才队伍
    weight: 40
  - name: 学术带头人
    parent: 人才队伍
    url: /people/
    weight: 10
  - name: 研究团队
    parent: 人才队伍
    url: /people/
    weight: 20
  - name: 研究人员
    parent: 人才队伍
    url: /people/
    weight: 30
  - name: 荣誉
    parent: 人才队伍
    url: /
    weight: 40


  - name: 开放数据
    identifier: 开放数据
    weight: 50
  - name: 开放数据中心
    parent: 开放数据
    url: /datasets/
    weight: 10
  - name: 物理海洋类
    parent: 开放数据
    url: /datasets/physical-oceanography/
    weight: 20
  - name: 海洋生态类
    parent: 开放数据
    url: /datasets/biochemical-oceanography/
    weight: 30
  - name: 海洋遥感类
    parent: 开放数据
    url: /datasets/remote-oceanography/
    weight: 40

  - name: 研究成果
    identifier: 研究成果
    weight: 60
  - name: 承接项目列表
    parent: 研究成果
    url: /projects/
    weight: 10
  - name: 论文发表列表
    parent: 研究成果
    url: /publications/
    weight: 20
  - name: 专利申请列表
    parent: 研究成果
    url: /patents/
    weight: 30
  - name: 获奖列表
    parent: 研究成果
    url: /
    weight: 40

  - name: 社会服务
    identifier: 社会服务
    weight: 70
  - name: 产品技术
    parent: 社会服务
    url: /social-service/product-technology/
    weight: 10
  - name: 成果转化
    parent: 社会服务
    url: /publications/
    weight: 20
  - name: 应用案例
    parent: 社会服务
    url: /social-service/applications/
    weight: 30



